name: Backend task
description: Шаблон с необходимыми полями для backend задач
title: "[дд.мм]: "
labels: ["backend"]
body:
  - type: input
    id: contact
    attributes:
      label: Кого надо уведомить?
      description: Укажите ник в тг или имя, фамилию
      placeholder: tg @
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Описание 
      description: Текстовое описание, что нужно сделать в задаче, или ссылка на требования
    validations:
      required: true
  - type: textarea
    id: deploy
    attributes:
      label: План деплоя
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    validations:
      required: false
  - type: textarea
    id: backend
    attributes:
      label: Комментарий Backend
    validations:
      required: false
  - type: textarea
    id: qa
    attributes:
      label: Комментарий QA
    validations:
      required: false
