name: 🐞 Bug
description: Новый шаблон для багов
title: "Краткое описание проблемы, идеально в формате Что? Где? Когда?"
type: "Bug"
body:
  - type: input
    id: environment
    attributes:
      label: Среда
      description: В какой среде проявляется ошибка (например, прод, локально)?
      placeholder: прод и локально
    validations:
      required: true
  - type: input
    attributes:
      label: Ссылка
      description: Ссылка на основную / связанную задачу, Pull request или на сообщение в боте с багами
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Нужно кого-то уведомить после исправления / деплоя?
      description: Укажите ник в тг или Имя и Фамилию
      placeholder: tg @
    validations:
      required: false
  - type: textarea
    id: preconditions
    attributes:
      label: Предусловия
      description: Описание необходимого состояния системы до шагов воспроизведения
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Шаги для воспроизведения
      description: Перечислите пошагово, как воспроизвести баг
      placeholder: |
        1. Перейти на страницу ...
        2. Нажать на кнопку ...
        3. Обратить внимание на ...
    validations:
      required: true
  - type: textarea
    id: fact-behavior
    attributes:
      label: Фактический результат
      description: Описание того, что увидели после выполнения шагов воспроизведения. Что именно не так?
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Ожидаемый результат
      description: Ясное и однозначное описание того, что ожидали увидеть, можно выдержкой из требований. Не забудьте указать ссылку на требования. Если на текущий момент нет требований, то упомянуть того, кто опишет требования здесь.
      placeholder: "Например: должно было появиться сообщение об успешной отправке формы"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Логи / скриншоты / ошибки в консоли
      description: Вставьте сюда серверные логи (текст и ссылку), ошибки из консоли (текст) или добавьте скриншоты. Большой текст можно спрятать под [спойлер](https://outlinewiki.onliner.org/doc/kak-opisyvat-zadachi-bagi-rekomendacii-JYs86jqyh5#h-dopolnitelьnaya-informaciya-i-ssylki) или добавить ссылку на gist
    validations:
      required: false
  - type: textarea
    id: browser-version
    attributes:
      label: Браузер / платформа / версия устройства
      description: Уточните, если баг воспроизводится не везде
      placeholder: 'Например: Chrome 125.0.6422.113 (macOS Sonoma 14.5)'
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Дополнительная информация
    validations:
      required: false
  - type: textarea
    id: bug-priority
    attributes:
      label: Критичность бага
      description: Уточните проритезацию бага, если он из бота. Документация [здесь](https://outlinewiki.onliner.org/doc/prioritizaciya-bagov-iz-bota-b0jqwK3zJe)
      value: |
        Критичность 3
        Частота 4
        Влияние 3
        Итоговый приоритет 10 - P2
    validations:
      required: false
